{{- if and .Values.imagePullSecret .Values.imagePullSecret.name .Values.imagePullSecret.dockerConfigJson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerConfigJson }}
{{- end }}
